### ISSUE TITLE
Change venue from LAB Miami => CIC Miami

### ISSUE THREAD

**Issue by ErnieAtLYD** [CodeforSouth/old-code-for-miami-website-archived-#13]
Starting Labor Day we are moving Code for Miami weekly hack nights to CIC Miami. The web pages should be changed to reflect this.

**Comment by fullstackmiami** [comment]
#17 #15

**Comment by ErnieAtLYD** [comment]
👍  By the way, in the future, if you use the phrase `fixes #17, fixes #15` it will automatically make reference to the github issues when the PR is approved: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by fullstackmiami** [comment]
Sweet, thanks 👍
